baseURL = "https://cis-3500-team9-extension.org/"
languageCode = "en-us"
title = "Yelper"
theme = "simple"
 # Path to site logo file under /static/images
 [params]
   logo = "5baf4e7d-509e-4806-a825-478ea452eca1_removalai_preview.png"
publishDir = "../docs"

[menu]
  [[menu.main]]
    name = "Features"
    url = "/features/"
    weight = 1
  [[menu.main]]
    name = "Screenshots"
    url = "#screenshots"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 3
